services:
  db:
    image: postgres:15
    container_name: messenger_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: messenger_redis
    restart: always
    expose:
      - "6379"
  web:
    build: .
    container_name: messenger_web
    restart: always
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      PYTHONPATH: /app/src
      RATELIMIT_STORAGE_URI: redis://messenger_redis:6379
    volumes:
      - .:/app
      - /app/.pixi
    depends_on:
      - db
      - redis
    expose:
      - "5000"

  nginx:
    image: nginx:latest
    container_name: messenger_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Certyfikaty
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./src/app/static:/app/static:ro
    depends_on:
      - web

volumes:
  postgres_data: